BUY_SUBSCRIPTION = "خرید اشتراک"
MY_SUBSCRIPTIONS = "اشتراک های من"
WALLET = "کیف پول"
PROFILE = "حساب کاربری"
TUTORIAL = "آموزش"
EARN = "کسب درآمد"
SUPPORT = "پشتیبانی"
ADMIN_PANEL = "پنل ادمین"

ADMIN_PLANS = "مدیریت پلن ها"
ADMIN_QUOTA = "ظرفیت فروش"
ADMIN_USERS = "کاربران"
ADMIN_PAYMENTS = "پرداخت های در انتظار"
ADMIN_BROADCAST = "ارسال همگانی"
BACK = "بازگشت"
